### ISSUE TITLE
Invalid Project Format Exception if Project is new project file format

### ISSUE THREAD

**Issue by ManfredLange** [nunit/vs-project-loader#11]
If a solution contains at least one project (*.csproj) that is in the file format for .NET Core applications, vs-project-loader fails with exception. This prevents migrating scripts that invoke nunit3-console with the solution file where the solution file contains a mix of projects (e.g. .NET Core/.NET Standard and full .NET Framework).

I would like to suggest two possible solutions:

1. Addin vs-project-loader would indicate that it cannot handle the new file format and that way allow the implementation of other addins who can.
2. Addin vs-project-loader is modified to also being able to handle the new project file format

Note: The project was created using the latest template for a .NET Core Console application in Visual Studio 2017 with all the latest patches/updates/etc applied.

Perhaps if I have overlooked something please let me know, e.g. if you are planning to take a different route to support the new project file format. I have a locally patched version of this addin that works for us but I do not think that it is good enough for a pull request. Happy to make the modified source file available without warranty that it will work in other environments. Let me know. It's more like a hack than anything.

**Comment by ChrisMaddock** [comment]
> if you are planning to take a different route to support the new project file format.

I don't think we have a plan yet! 😄 

This extension often faces issues when new project formats are released, as it reads the xml manually, and therefore falls over if this xml changes. This seems to be the best path of attack, in .NET 2.0, which this extension currently supports.

I've considered before trying to write a non-.NET-2.0 version, using the [Microsoft Build NuGet packages](https://www.nuget.org/packages/Microsoft.Build/15.3.0-preview-000388-01) - this is never something I've actually made progress on however. Theoretically, we could package both assemblies in the NUnit.Vs.Project.Loader package, and the engine could resolve the highest possible extension, for the platform it is currently running on.

That's a much bigger idea though - and something I've been thinking of for a couple of years, and still haven't made the time for. It may never happen! What's your hack - would you put up a PR, and @nunit/engine-team can see what we think? In my opinion, a well commented hack is better than nothing!

**Comment by ManfredLange** [comment]
Thanks, Chris. I'll create a fork and create a PR. I have never done a PR, so would like to ask for some patience if I don't get it right the first time. Thanks! I won't be able to do the PR right away but hopefully next weekend allows me to set aside some time for this.

**Comment by ChrisMaddock** [comment]
@ManfredLange - Great! No problem - expect us not to 'get it right first time' too, there's often a bit of back and forth while we all figure out the best approach to the problem - but there's a good team here to help. 🙂 

I didn't know that about MSBuild - nightmare! Maybe I can put this off for another year or two, once all the changes have settled down a little. ;-)

**Comment by jnm2** [comment]
@ChrisMaddock I've tried the MSBuild NuGet package route too but that's a dead end until we get https://github.com/Microsoft/msbuild/issues/1436.

**Comment by ChrisMaddock** [comment]
@jnm2 - I thought the Microsoft.Build package I linked to was that! Sounds like you've dug into this more than I have...I'll take it I'm wrong. 😞

**Comment by jnm2** [comment]
@ChrisMaddock Yep, I played with it for an evening. 😞 That's just MBuild itself with no C# .targets.

**Comment by ManfredLange** [comment]
Here is the link to the msbuild issue when build dependencies are treated as project references [https://github.com/Microsoft/msbuild/issues/2274](https://github.com/Microsoft/msbuild/issues/2274). 

We have worked around this issue by building a little tool that reads the solution file, all project files in the solution then create our own build order.

**Comment by ManfredLange** [comment]
Just sent a PR with a fix for this issue. Please let me know what you think.

**Comment by ManfredLange** [comment]
Four of the tests I added are failing on Travis. I can't reproduce locally at the moment. If you could give me a hint for how to find out what environment Travis is using I might be able to reproduce and then fix those tests.

**Comment by CharliePoole** [comment]
Closed by PR #12
