### ISSUE TITLE
NullReferenceException when loading project file with missing AssemblyName/OutputType

### ISSUE THREAD

**Issue by mrshanahan** [nunit/vs-project-loader#14]
I work some VB/C# projects which (for whatever reason) don't have `AssemblyName` or `OutputType` elements in their project XML. Visual Studio loads and msbuild builds these projects perfectly well, but attempting to load a solution containing them via nunit3-console throws a `NullReferenceException`. I didn't realize what the problem was until I pulled down the vs-project-loader code and looked at the relevant methods in the stack trace (namely, the `assemblyName.InnerText` and `outputTypeElement.InnerText` lines in `VSProject.cs:LoadMSBuildProject`).

I'm fine if vs-project-loader errors out when attempting to load these project files, but it would be nice if I didn't have to dig into the code to see what exactly was wrong with the file. Willing to submit a PR myself to throw a more specific exception. Thanks!

**Comment by CharliePoole** [comment]
We'd be glad to have a PR for this.

**Comment by CharliePoole** [comment]
I'm all for moving as fast as we reasonably can, but this issue was PRed, approved and merged without any initial triage and without a second review. I've made some comments on the PR.

Essentially, I would like to know whether throwing an exception produces the correct result here. What __should__ happen ideally is that we successfully return a package containing the assembly produced by the project. Since an assembly __is__ produced by VS, there should be some way to determine what it is.

Secondarily, if we have to have an exception until we actually solve this problem, then I'd like to know - either through a test or at least a comment from the OP - that throwing the exception gives the correct result to somebody running the test. What happens, for example, if there are other projects or assemblies on the command-line, or if the solution is used? Do the remaining projects and assemblies get treated correctly?

**Comment by ChrisMaddock** [comment]
Sorry - I should have waited for a second review. Mental block

**Comment by CharliePoole** [comment]
I think the big issue is whether we can do more than just throw an exception. How does VS figure out where to put the output in these cases? Can't we do the same thing?

**Comment by mrshanahan** [comment]
From what I can tell, in the absence of an explicit OutputType Visual Studio assumes that the OutputType is Library, and in the absence of an explicit AssemblyName it uses the file name of the project minus the extension. I'll double-check both of those.

I'm not sure if this is explicitly documented anywhere, which is why I'm wary of creating that kind of dependency (e.g. if the default behavior changes users would get an error saying that a file that shouldn't exist, doesn't exist). But it would certainly improve usability and I doubt that that behavior will change anytime soon, so if you're good with it I'll be happy to make that change!

**Comment by CharliePoole** [comment]
@OsirisTerje @ManfredLange Do you have any input on this?

**Comment by mrshanahan** [comment]
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties

Following up on my previous comment - the OutputType property explicitly
defaults to Library, so we don't have to throw there. This doc doesn't say
that AssemblyName defaults to project name, but other places in the
documentation do. It seems pretty safe to make those assumptions then.

**Comment by ManfredLange** [comment]
I'll have a look at the suggested PR. On first view - and I might be wrong - it appears to be addressing an issue for the old project file format and not for the new .NET Core format.

**Comment by mrshanahan** [comment]
True, this is something that specifically targets MsBuild file formats. I
just saw that you added an AssemblyName check for .NET Core projects, and
so I added something similar for the older format.

**Comment by CharliePoole** [comment]
@mrshanahan Do you by chance know how these projects were created?

**Comment by mrshanahan** [comment]
@CharliePoole From a quick glance through my company's Git history, they originally included both properties, but one or the other had been removed (probably accidentally) through programmatic changes to project files across the repo. Since they still built and with the correct name/extension it just went undetected.

**Comment by pavzaj** [comment]
Hello. Adapter still does not work if I have multitargeted project using <TargetFrameworks> tag instead <TargetFramework> tag in csproj. I presume that's multitargeting issue and wont be solved here, am I right?

**Comment by ChrisMaddock** [comment]
Fixed by https://github.com/nunit/vs-project-loader/pull/18

@pavzaj - your issue has been fixed in master. We're aiming to do another release soon, in the meantime, you could build from source.

**Comment by pavzaj** [comment]
Thanks
