### ISSUE TITLE
3.7 Release

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/vs-project-loader#19]
There's been a few important contributions to this project to support the new csproj format, which would be good to get into a release.

I'm happy to do the leg-work for that this weekend, unless anyone else would prefer to, or sees reason to hold off on it.

**Comment by CharliePoole** [comment]
Good idea. Once you do, I suggest filing an issue to test it with the next release for bundling. In theory, you should test the changes with existing releases at the point where you release the new extension since a user can mix them in.

**Comment by ChrisMaddock** [comment]
I've added the 3.7 release to this repository. I tested manually with the latest version release of the console.

@rprouse - would you please upload the packages to NuGet and Chocolatey when you get a chance?

I will shortly:
- [ ] Add a news item to nunit.org
- [ ] PR an update the the NUnit.Console packages
- [ ] Update the version numbers here so that master is on 3.8.

**Comment by rprouse** [comment]
I've uploaded to NuGet.org. I don't have permissions on Chocolatey, only @CharliePoole does. If you want to add me, I can upload, or you can take care of it @CharliePoole.

**Comment by ChrisMaddock** [comment]
@CharliePoole - would you be able to sort out the Choco upload? 🙂

**Comment by CharliePoole** [comment]
I can upload. Have you tested it?

**Comment by ChrisMaddock** [comment]
I tested the assembly yes. I haven't tested the choco packaging, but I assume that hasn't changed!

**Comment by CharliePoole** [comment]
I downloaded the package from GitHub, gave it a quick look and then uploaded to chocolatey. Waiting for verification.

**Comment by ChrisMaddock** [comment]
Great, thanks! Once that goes through, that's everything for the release, so I'll close this issue now.
