### ISSUE TITLE
3.8 Release

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/vs-project-loader#29]
I'd like to do another release of this extension - it's been a year since the last one, and there's been one fix committed to master, one that @mrjpeterj has identified and is working on, and a third open PR from @gavardev. 

I'd like to wait for the above two issues to be merged/closed - anyone have any other reason to hold on?

**Comment by ChrisMaddock** [comment]
Ping @rprouse - now you're back - just to check, are you happy for me to go ahead with this?

**Comment by rprouse** [comment]
@ChrisMaddock go ahead with a release once you feel it is ready. After you do so, update the console w/ extensions nuspec.

**Comment by ChrisMaddock** [comment]
Package has been released to GitHub. Choco upload seems to be timing out at the moment unfortunately...will have to try again later.

@rprouse - would you be able to complete the last two steps, please? 😄 
 - [ ] Upload the NuGet package [here](https://github.com/nunit/vs-project-loader/releases/tag/v3.8) to nuget.org
 - [ ] Publish the website news post at https://github.com/nunit/nunit.github.io/pull/53

Also todo:
 - [ ] Upload to Chocolatey when chocolatey.org is back online

**Comment by ChrisMaddock** [comment]
Apparently choco.org upload has a few issues, but `choco push` was working - thanks for the tip @gep13!

**Comment by rprouse** [comment]
Tasks completed. I also entered https://github.com/nunit/nunit-console/issues/450 to update the Console Runner w/ extensions package. I just noticed above that you already have a PR for that. I will link them.

**Comment by ChrisMaddock** [comment]
Great - thanks Rob!
