### ISSUE TITLE
Unable to choose platform when passing solution file

### ISSUE THREAD

**Issue by akorczynskikcura** [nunit/vs-project-loader#34]
If I execute command `nunit3-console solution.sln` nunit-console is looking for assemblies in the wrong folder, for example \bin\x64 instead of \bin
As a result we get
```
1) Invalid : S:\...\bin\x64\some.dll
File not found: S:\...\bin\x64\some.dll
```
We have two platforms in the code: AnyCPU and x64 and for the build itself we're calling Release and AnyCPU. We would like to then call nunit-console to run the tests

I tried supplying config parameter `nunit3-console solution.sln --config="Release|AnyCPU"` but I got
```
1) Invalid : S:\...\solution.sln
File type is not supported
```
Please advise how to run our tests with correct configuration/platform (Release and AnyCPU)

**Comment by akorczynskikcura** [comment]
I cannot share files, but I can add some snippets. This is how global section in sln file looks like

```
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Debug|x64 = Debug|x64
		Release|Any CPU = Release|Any CPU
		Release|x64 = Release|x64
	EndGlobalSection
```
And this is how a typical project looks like

```
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x64</Platform>
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>[projectName]</RootNamespace>
    <AssemblyName>[projectName]</AssemblyName>
    <TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <TargetFrameworkProfile />
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\Solutions\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <ErrorReport>prompt</ErrorReport>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>full</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <OutputPath>bin\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <LangVersion>7.3</LangVersion>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
```

**Comment by ChrisMaddock** [comment]
Hey @akorczynskikcura - I believe the `--config` flag is only intended to allow you to target Release or Debug, and not a particular platform (e.g. AnyCPU or x64).

I don't believe there's a way to do that currently - although someone else may correct me.

**Comment by CharliePoole** [comment]
@ChrisMaddock That's correct, --config expects to select a particular $(Configuration), which is assumed to be unique. The project leader can't handle two different Release configs.

Also, why have both AnyCpu and X64, since AnyCpu just means it runs on either X64 or X86?

**Comment by CharliePoole** [comment]
@ChrisMaddock That's correct, --config expects to select a particular $(Configuration), which is assumed to be unique. The project leader can't handle two different Release configs.

Also, why have both AnyCpu and X64, since AnyCpu just means it runs on either X64 or X86?

**Comment by akorczynskikcura** [comment]
@CharliePoole it's a long story but we had issues with some packages with AnyCPU, that's why we have x64, which is the default right now. We are still trying to make AnyCPU work.
Is it true that VS project loader picks default platform, which, looking at project files, is x64 now and there is no way to make it choose another platform ?

**Comment by CharliePoole** [comment]
The project loader doesn't pick the platform at all. On request, it returns a `TestPackage`, which is what the engine needs to load it. The `TestPackage for a solution contains nested `TestPackage`s for each contained project. The `TestPackage` for a project contains the output assembly path. It does __not__ contain any settings. for how to build or run the project, that's up to VS.

Contrary to what I wrote earlier, the names of configs in the projects __do__ contain the platform, with the exception of `AnyCpu`, which is removed. So your project would have configs `Debug`, `Debug|X64`, `Release` and `Release|X64`. In retrospect, it's obvious that this is confusing, but` it was intended to simplify life for most users, who were presumed to use `AnyCpu`.

If you don't specify the config on the command line, NUnit uses the first config it finds. Best bet would be to specify it.

**Comment by akorczynskikcura** [comment]
@CharliePoole, so in my case if I specify just `--config="Release"` it would actually mean `"Release|AnyCPU"` and I don't specify anything it would pick default, in my case `"Debug|x64"` ?

I tested that and if I specify just `--config="Release"` I get two errors:

- `No suitable tests found` for the expected path from AnyCPU (this assembly holds no tests, I would expect nunit-console to ignore any assemblies not containing tests) 

and also 

- `file not found` for the \bin\x64 path for the same assembly.

I also tried `--config="Release|x64"` just to test if this works and I get the `File type is not supported` before trying to run any tests, so I do not see this 'configuration|platform' syntax supported.

I should clarify that I'm using nunit-console version **3.9.0.**

**Comment by CharliePoole** [comment]
If you tell NUnit3-console to run tests from an assembly with no tests, then that's treated as an error. In this case, you are telling it to do so indirectly, by use of a solution. The project loader would need to be much smarter to avoid the error. However, __you__ know you are loading a solution, so you can tell the console to ignore the error via the `--skipnontestassemblies` option.

WRT `--config="Release|X64"`, you may need to escape `|` on the command-line according to the conventions of the OS you are using. I'm not sure of this.

As you can see in the commits, I haven't worked on this for a few years. @ChrisMaddock can you add anything?

**Comment by ChrisMaddock** [comment]
Sorry - I've never actually worked on this extension, I just pushed out the last release. Afraid it's not one I'm familiar with.

**Comment by CharliePoole** [comment]
Looks like most work for the past few years has been contributed.

AFAICS, there are no tests for duplicate config names as used in this example. Somebody will have to confirm, but I am guessing it's a bug. Adding tests would be one way to confirm if @akorczynskikcura has time and interest in making a contribution. :smiling_imp: 

Eventually, I'll probably circle back to this, but I have lots of other work right now.

I'd like to bring up an earlier suggestion I made, which is to remove support for VS solutions - perhaps in NUnit 4. The reason I suggest this is that there is no way for NUnit to know which projects in a solution are actually test projects, so the `TestPackage` that is created includes all the projects, with only a few exceptions.

**Comment by akorczynskikcura** [comment]
I did some more tests and `--skipnontestassemblies` does not quiet the `File not found` error. I even tried to move AnyCPU configuration sections above x64 in csproj, but it didn't help either.

I would think it's an issue many people having more than one configuration would notice.

**Comment by CharliePoole** [comment]
No it's only intended to ignore the "error" of trying to run a non-test assembly. Ideally, the project leader for solutions should have supplied this setting automatically.

OTOH the not found error is real, even if caused by a bug.

**Comment by akorczynskikcura** [comment]
Yes, 'not found' is real, there is no such assembly there. The point is that it should not be looking there.

I checked loader source code and even prepared data and wrote some tests. It looks like the code deliberately removes anything past | mark. It also seems to be more of a problem with solution loader than project loader. Project loader loads all solutions with the exceptions of `|AnyCPU` as you pointed out, so Debug, Release, Debug|x64 and Release|x64, but the solution loader, when comparing its configurations with project configurations, returns only 'Debug' and 'Release' configurations back to nunit. Not sure if it matters, but projects have `AnyCPU`. but solutions have `Any CPU' (with space). I was thining of fixing this somehow, but I really don't know what are the expected values from NUnit perspective and what it can consume and what not.

Workaround I found so far is to remove x64 configuration and leave only one Any CPU on solution level. For projects I did not have to make any changes.

**Comment by CharliePoole** [comment]
Yes, I was responding WRT project configs, not solution configs. May be useful for whomever fixes this to know that we originally only used project configs but then retrofitted solution configs when a solution is involved due to a bug report.

**Comment by CharliePoole** [comment]
Well, after all this time, it turns out that I'm the one fixing it! Glad I left that last comment for myself. :-)

**Comment by CharliePoole** [comment]
@akorczynskikcura I'm closing this as fixed, although all I have actually done is add at test that shows it works as designed. It's possible that some other change since the last release fixed it. But it's also possible that I've missed something. :-(

Can you try out the build with the fix from https://www.myget.org/feed/nunit/package/nuget/NUnit.Extension.VSProjectLoader/3.9.0-dev00047 (nuget) or https://www.myget.org/feed/nunit/package/nuget/nunit-extension-vs-project-loader/3.9.0-dev00047 (chocolatey) and let me know how it works for you? If it still doesn't work, we can reopen this.

A note about expectations:

To NUnit, the config is simply "Debug" or "Release" (or some other config name) When you run your solution using one of them (or the default) you should see your tests run for all three platforms, using the proper output paths. The console runner has no way to select a particular platform, so the extension doesn't support it either.
